version: '3.8'

services:
  code_processor_app:
    container_name: code_processor_app
    build:
      context: ../
      dockerfile: ./cmd/app/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GIN_MODE=debug
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - code_processor_network

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - code_processor_network

  code_processor_worker:
    container_name: code_processor_worker
    build:
      context: ../
      dockerfile: ./cmd/processor/Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - SERVER_URL=http://code_processor_app:8000
    depends_on:
      rabbitmq:
        condition: service_healthy
      code_processor_app:
        condition: service_started
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - code_processor_network

  tests:
    container_name: code_processor_tests
    build:
      context: ../
      dockerfile: ./tests/Dockerfile
    environment:
      - BASE_URL=http://code_processor_app:8000
    depends_on:
      code_processor_app:
        condition: service_started
      code_processor_worker:
        condition: service_started
    networks:
      - code_processor_network

networks:
  code_processor_network:
    driver: bridge